# This workflow will run tests with coverage and upload the results to Codecov
# To enable Codecov integration:
# 1. Sign up at https://codecov.io (free for open source)
# 2. Add your repository to Codecov
# 3. Optionally, add CODECOV_TOKEN as a secret in your repository settings
#    (not required for public repositories)

name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod download

    - name: Run tests with full instrumentation coverage
      run: |
        # Instrument application packages and run all tests (including external tests under ./tests)
        go test -short -v \
          -covermode=atomic \
          -coverpkg=./internal/...,./pkg/... \
          ./... \
          -coverprofile=coverage.txt
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-learn-api
        fail_ci_if_error: false  # Optional: Set to true if you want CI to fail when Codecov fails
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.txt
